### ISSUE TITLE
Visual studio build quirk(s)

### ISSUE THREAD

**Issue by toxieainc** [trzy/Supermodel#203]
Using my own VS2022/2019 builds, e.g. both Daytona 2 games and Scud Race feature a quirk where it seems the gas pedal (all pedals?) is stuck pressed at the beginning of the race, but only on certain tracks (e.g. on D2 medium/advanced course, SR expert course).

This does not happen with the official gcc based build.

**Comment by dukeeeey** [comment]
My guess is our friend the uninitialized variable. I fixed a whole bunch but there are more.

**Comment by gm-matthew** [comment]
Maybe it's worth trying a clean build? Try compiling with Rebuild Solution instead of Build Solution and see if it changes anything.

Occasionally I'll get weird issues - usually Supermodel failing to start - that are fixed by making a clean build. Also I personally turn off link-time code generation (LTCG) since that seems to make corrupt builds less frequent.

**Comment by toxieainc** [comment]
Yes, i already tried all kinds of things. Also changing various compiler options, and trying to init more class members (just to be sure), but so far the problem remains with the VS builds.

**Comment by toxieainc** [comment]
I guess next step would be to run a real mem tracker like Dr.Memory on it to see where/if uninit'ed mem is used or if there is some other unknown glitch.

**Comment by toxieainc** [comment]
So far no luck with uninit'ed mem.  :/
The tool reports tons of issues in the Intel GFX driver though  ;)

**Comment by trzy** [comment]
Have you tried some good old fashioned printf() debugging to see where the input values appear to be corrupted? Starting to suspect a code generation issue and unfortunately, it's somewhere in the CPU emulator, it'll be hard to find, but you'll be able to assess at least whether the input system is returning the expected values (which would indicate something is happening downstream in the CPU emulator). I haven't tried building with MSVC yet but this shouldn't be too hard to debug. I may be able to look into it after Monday. Does it also happen when the debugger is built? If so, the debugger will be immensely helpful. Input values are usually read once per frame in a single place.

**Comment by toxieainc** [comment]
@trzy ReadInputs() does not show any activity for Steer,Acc or Break for the m_game.inputs & Game::INPUT_VEHICLE case.
Or is there more to check?

**Comment by trzy** [comment]
This sounds bad. But: does it show activity when compiled with gcc or in the stages where it works? If so (and I do think it should unless I am missing something obvious), then I think the problem is inside the input system.

**Comment by toxieainc** [comment]
Misunderstanding. It works if i press keys, etc, but it does not show any activity if not pressing anything, so the problem that the car seems to have acceleration and brake pressed does not seem to come from the inputs.

**Comment by toxieainc** [comment]
@trzy Any other hints what/how i could continue debugging?

**Comment by trzy** [comment]
You’ll have to trace deeper into the actual game code. What I typically do is 1) compile with debugger enabled and 2) to find the program counter address where some register is accessed, I place a printf() statement that prints the value of ppc_get_pc() in the appropriate handler (in this case, the function in Model 3 that returns analog inputs). Unfortunately, it will then become a more painful process because you’ll have to figure out where these inputs ultimately get stored in the game’s RAM, where they are picked up by other parts of the game code, etc. I don’t think the debugger has memory watches (maybe it does?) but, depending on where in RAM they are stored, sometimes they are accessed using a consistent register addressing mode that is text-searchable in the game code. You can then disassemble the entire game (from the RAM dump using ppcd, which is buildable by setting a macro in PPCDisasm.cpp) and try to identify points where the steering inputs are read. 

The problem is, who knows how deep the problem runs. 

Just off the top of my head, one potential culprit is the floating point code. Can you play with MSVC optimization options, specifically around floating point math?

**Comment by toxieainc** [comment]
Okay, thanks! I fear i will not have enough spare time soon to really dig into this problem THAT deep.
But i will try to fool around with compiler options.

**Comment by trzy** [comment]
The more I think about it the more it seems likely that the culprit is something like FP math or some other weird instruction.There used to be a PowerPC emulator stress tester — I think part of the SheepShaver project. There might also be a regression tester in Dolphin we could borrow. Sent from my iPhoneOn Oct 17, 2024, at 12:48 AM, toxie ***@***.***> wrote:﻿
Okay, thanks! I fear i will not have enough spare time soon to really dig into this problem THAT deep.
But i will try to fool around with compiler options.

**Comment by toxieainc** [comment]
Okay, so basically in the PPC core then?

**Comment by trzy** [comment]
That’s where I’d look first. Quick things to check also, as sanity checks, are that the final values returned from the relevant functions in Model3.cpp (the register handlers, at the final return statement) are as expected and not being corrupted there. Also the read handlers themselves, e.g. Read8(), contain a big switch statement. Can’t imagine any problem there but it’s one more place to do some sanity testing in. Besides that I think the most likely culprit is either the floating point code setting some PowerPC flag incorrectly, thereby causing a branch to go awry, or some other weird condition. I wouldn’t over index on float stuff just because I suggested it but it’s one place to start where I think we had seen trouble before (albeit across all compilers because the code was just wrong).In this case, it really does smell like a code generation or optimization issue if gcc and clang don’t have a problem.Sent from my iPhoneOn Oct 17, 2024, at 1:42 AM, toxie ***@***.***> wrote:﻿
Okay, so basically in the PPC core then?

**Comment by toxieainc** [comment]
Is the gcc or clang path compiled with fast-math?

**Comment by trzy** [comment]
Nope not that I can see. Rules.inc and Makefile.Win32 don’t have that. They just use -O3 and set C++17 mode.Sent from my iPhoneOn Oct 17, 2024, at 1:06 PM, toxie ***@***.***> wrote:﻿
Is the gcc or clang path compiled with fast-math?

**Comment by dukeeeey** [comment]
Have you tried a 32bit vs 64bit build?

**Comment by toxieainc** [comment]
I really nailed it down to the math opts now. Looking into what is causing it now.

**Comment by trzy** [comment]
How did you narrow it down?Sent from my iPhoneOn Oct 17, 2024, at 1:38 PM, toxie ***@***.***> wrote:﻿
I really nailed it down to the math opts in PPC now. Looking into what is causing it now.

**Comment by toxieainc** [comment]
Switching compile options. And the ppc files are the only ones that 'reacted' to this (=causing the misbehavior).
I still want to track down the exact place(s)/function(s) in there, so that hopefully we could just make things more explicit and in the future could enable more aggressive optimizations if needed.

**Comment by dukeeeey** [comment]
Im sure the rounding mode for the project got changed at some point which effects the powerpc float rounding

**Comment by toxieainc** [comment]
Yes, i saw that. And in some sense this is also a bit risky. From my understanding so far, the rounding mode is changed, as soon as the game code calls that opcode. The problem is that this is done 'globally', so all other Supermodel code will also be affected by that then.
Thats also something i want to look into.

**Comment by toxieainc** [comment]
Oh my. Going forward, the only reliable solution seems to be to emulate all rounding modes 'by hand' for each PPC fp instruction.
Only visual c++ seems to offer a reliable way to set the rounding mode, and while gcc and clang offer a compile option, in practice that one seems to be not fully reliable.  :/

**Comment by trzy** [comment]
Why does it work in gcc and clang then? And are we sure this error is due to rounding modes?

**Comment by dukeeeey** [comment]
[https://en.cppreference.com/w/cpp/numeric/fenv/feround](url)

**Comment by toxieainc** [comment]
Yes, its 100% due to the rounding modes. I will fix this for visual c++, as it provides a reliable way to support fesetround.
But going forward, gcc and clang may just also show bad behavior at some point from what i read, as the behavior there is not well defined, even with -frounding-math enabled.

Plus, what i think is even worse, fesetround changes behavior not just for the PPC code parts, but globally for all fp operations in supermodel.

**Comment by toxieainc** [comment]
I now fixed all the mentioned issues above in aboves PR.

The only caveat is that the GCC and clang behavior is still based on 'luck', same as before. So you guys should definetly enable -frounding-math for GCC and clang, but according to my net research the behavior even then is still not well defined.
But all other solutions, like manually emulating the rounding modes, would be total overkill though and also not exactly trivial.

Sidenote: The FMA PPC opcodes may suffer from insufficient precision (as for the double variants its not actually fused).
And also all NaN checks may be optimized away if one turns on aggressive math optimizations (which is not the case at the moment i think).

**Comment by gm-matthew** [comment]
> Sidenote: The FMA PPC opcodes may suffer from insufficient precision (as for the double variants its not actually fused). And also all NaN checks may be optimized away if one turns on aggressive math optimizations (which is not the case at the moment i think).

I believe that the way nearly all of the floating point arithmetic instructions work on PowerPC is that they use an FMA unit with a 56x28 bit multiplier, where fmul sets FRB to 0.0 and fadd sets FRC to 1.0. Double precision multiplies require two cycles; one to multiply the higher bits of FRC and one to multiply the lower bits, and the two results are added as a part of the second FMA operation.

I have a PowerBook with a PowerPC 603 which I used to fix a rounding issue that was causing the car to go off track in the attract mode of Daytona 2 BOTE; I could use it to help make the floating point instructions even more accurate if so desired.

**Comment by toxieainc** [comment]
Thanks for the feedback! I would assume that double precision isn't used much if these take double the cycles.
Are the fp32 opcodes okay like-is?

**Comment by toxieainc** [comment]
@gm-matthew Also one more thing i noticed:
In `ppc_fctiwx` this seems wrong to me:
`if(FPR(b).fd < (INT64)((INT32)0x80000000))`
shouldn't this be
`if(r < (INT64)((INT32)0x80000000))`

**Comment by gm-matthew** [comment]
> @gm-matthew Also one more thing i noticed: In `ppc_fctiwx` this seems wrong to me: `if(FPR(b).fd < (INT64)((INT32)0x80000000))` shouldn't this be `if(r < (INT64)((INT32)0x80000000))`

I think you're right, probably a good idea to fix it. That dates back to the very first public release of Supermodel in 2011!

**Comment by trzy** [comment]
I notice that there’s a bunch of commented out code dealing with rounding. Could that be rehabilitated to make rounding behavior more deterministic and consistent across compilers?Sent from my iPhoneOn Oct 20, 2024, at 1:48 PM, Matthew Daniels ***@***.***> wrote:﻿

@gm-matthew Also one more thing i noticed: In ppc_fctiwx this seems wrong to me: if(FPR(b).fd < (INT64)((INT32)0x80000000)) shouldn't this be if(r < (INT64)((INT32)0x80000000))

I think you're right, probably a good idea to fix it. That dates back to the very first public release of Supermodel in 2011!

**Comment by toxieainc** [comment]
No, unfortunately not.
But also note that changing the rounding mode is not common, so i think after this PR we should be pretty good with how things are now.

**Comment by toxieainc** [comment]
Note that i redid the PR because of a stupid copy paste error in the commit message  :/

**Comment by toxieainc** [comment]
Hmmm.. I found another thing in the PPC core that looks wrong to me:
`is_qnan_double` has 3 flaws:
`0x0007fffffffffff` should be `0x0007ffffffffffff`, and `0x000800000000000` should be `0x0008000000000000`.
In addition it checks if the remaining frac bits are 0, but due to the IEEE spec these can be used for a payload.

Can anybody double check, please?

**Comment by toxieainc** [comment]
MAME PR was taken, so will add the tweak(s) to this PR here, too.

**Comment by toxieainc** [comment]
..and PR #216 is up to date

**Comment by toxieainc** [comment]
Found yet another bug in fctiw(z)x, will push that, too

**Comment by toxieainc** [comment]
and one more that can happen if the compiler is not strictly following NaN conventions

**Comment by toxieainc** [comment]
#216 ready

**Comment by toxieainc** [comment]
@gm-matthew You did tweak `fres` at some point to be less precise. But in fact it should be even less precise (approximation), but if i do what e.g. Dolphin uses, then i get weird behavior for some things (e.g. scud race attract mode has a very jittery car then). Any hints what i may have to look out for in addition?
btw: Using the suggested approximation for `frqrte` seems to work well.

**Comment by toxieainc** [comment]
Oh, and in addition: Does the 603 need to respect the NI flag that can lead to denormals being flushed to zero? I couldn't find anything so far on the net.

**Comment by toxieainc** [comment]
@gm-matthew As you offered help with your PPC based notebook: Could you please test what the result of frsqrte and fres are for '1.0'? Cause the implementation in Dolphin does not return 1.0 for both, leading to the jitter in scud race. Also this seems weird, as 1.0 is so easy to represent in fp32 and other CPUs also match that well.

**Comment by toxieainc** [comment]
One more ask if you're willing to test more: Some fp32 instructions run in less precision apparently (again Dolphin and CEmu), e.g. fmuls ditches some bits of the second input: https://github.com/cemu-project/Cemu/blob/63e1289bb518562ae62033389610a1e772e63c8b/src/Cafe/HW/Espresso/Interpreter/PPCInterpreterFPU.cpp#L581

**Comment by trzy** [comment]
I’m increasingly uncomfortable with some of these changes which do not reference primary documentation. We should not be copying Dolphin, which implements a very different processor, without first consulting the official PowerPC 603 documentation.Generally speaking, the floating point code seems to work pretty well except for a potential bug in MSVC (and has that Scud Race bug been pinpointed?). These are really high risk changes that should require a *complete* play through of every single game before being committed. Obvious errors are one thing but I think we should refrain from fixing anything that cannot be explicitly shown to be causing an emulation issue.Sent from my iPhoneOn Oct 26, 2024, at 9:08 AM, toxie ***@***.***> wrote:﻿
One more ask if you're willing to test more: Some fp32 instructions run in less precision apparently (again Dolphin and CEmu), e.g. fmuls ditches some bits of the second input: https://github.com/cemu-project/Cemu/blob/63e1289bb518562ae62033389610a1e772e63c8b/src/Cafe/HW/Espresso/Interpreter/PPCInterpreterFPU.cpp#L581

**Comment by toxieainc** [comment]
Absolutely, i fully agree. I'm currently just trying to find out what should be really happening, as fres and frsqrte should be approximations after all. Thats why i asked for comparsion to real HW.

The changes in #216 should be perfectly fine and finished.

**Comment by gm-matthew** [comment]
> @gm-matthew You did tweak `fres` at some point to be less precise. But in fact it should be even less precise (approximation), but if i do what e.g. Dolphin uses, then i get weird behavior for some things (e.g. scud race attract mode has a very jittery car then). Any hints what i may have to look out for in addition? btw: Using the suggested approximation for `frsqrte` seems to work well.

According to the [PowerPC 603e manual](https://www.nxp.com/docs/en/reference-manual/MPC603EUM.pdf), both fres and fdivs have a latency of 18 cycles. Testing on my PowerBook 1400cs confirmed that on the PowerPC 603e, fres is effectively equivalent to fdivs with FRA set to 1.0; the FPU performs an accurate divide to single precision.

The Gekko CPU (based on a PowerPC 750CXe) used in the GameCube performs fres by using a lookup table with interpolation to compute a much faster, but less accurate reciprocal.

fsqrte on the PowerPC 603e uses a 32-entry lookup table without interpolation to produce an approximate result, however all Model 3 games that I have seen use Newton's method to increase the accuracy of the result, so the actual result produced by the emulated frsqrte instruction doesn't really matter. I did create a proper implementation of frsqrte but in practice it had no effect, which is why so far I haven't bothered to actually merge it into the project.

**Comment by toxieainc** [comment]
Thanks a lot for the info on these 2 functions! I would still appreciate including the lower-precision fsqrte, even if its just as undefined code, in order to be able to experiment with any precision related issues.

You also mentioned
'FMA unit with a 56x28 bit multiplier, where fmul sets FRB to 0.0 and fadd sets FRC to 1.0'
That one could really mean that for single precision results the second inputs mantissa is limited in precision, right?
Again, this could be mainly helpful to have as an additional helper during debugging, so as an undefined code path that would do 'the right thing' optionally. After all, we saw at least 2 harsh bugs being fixed, by 2 seemingly harmless fixes (i.e. the scud/daytona pedal issue in here, and the above mentioned car-goes-off-track in daytona).

And any info on the denormalized fp math? I would assume that the 603 did not support that yet, but maybe you know for sure?

**Comment by toxieainc** [comment]
In case you could/want to verify the FMA limited precision, e.g. this is what is used on Gekko for all fp32 math including a mul:
```
static inline double roundTo25BitAccuracy(const FPR d)
{
	FPR result;
	result.id = (d.id & 0xFFFFFFFFF8000000ULL) + (d.id & 0x8000000ULL);
	return result.fd;
}

```
