### ISSUE TITLE
SCUD RACE ROLLING START GLITCH:

### ISSUE THREAD

**Issue by Garagefreek** [trzy/Supermodel#245]
Any luck or progress with the problem?

**Comment by dukeeeey** [comment]
It should already be fixed

**Comment by Garagefreek** [comment]
> It should already be fixed

![Image](https://github.com/user-attachments/assets/ee3cef35-3846-478e-8ca7-c5f6d30aefe8)

It's not fixed, this is from the latest git?
